# otelcol
# TODO: Configure OTel Collector
# https://opentelemetry.io/docs/collector/configuration/

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    # view /debug/tracez
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    # basic, normal, detailed
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

processors:
  batch: 
  memory_limiter:
    limit_mib: 2048
    spike_limit_mib: 512
    check_interval: 5s

  tail_sampling:
    decision_wait: 5s
    num_traces: 100
    expected_new_traces_per_sec: 5
    policies:
    - name: slow-trace
      type: latency 
      latency:
        threshold_ms: 1100
    - name: spans-with-errors
      type: status_code 
      status_code:
        status_codes: [ ERROR ]
    - name: keep-10-percent 
      type: probabilistic 
      probabilistic:
        sampling_percentage: 10

service:
  extensions: [ health_check, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, tail_sampling, batch ]
      exporters: [ debug, otlp/tempo, otlp/jaeger ]
