---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: task02-otelcol
  namespace: workshop04
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
  volumes:
  - name: hostfs
    hostPath: 
      path: /
      type: Directory
  volumeMounts:
  - name: hostfs
    mountPath: /hostfs
    readOnly: true

  config: 
    # Configuration goes here
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      zpages:
        # view /debug/tracez
        endpoint: 0.0.0.0:55679

    processors:
      batch: {}
      memory_limiter:
        limit_mib: 1024
        spike_limit_mib: 410
        check_interval: 5

    receivers:
      filelog:
        # filelog recevier configuration
        include:
          # /hostfs is where the node's files system is mounted
        - /hostfs/var/log/pods/workshop04_*/*/*.log
        exclude:
        - /hostfs/var/log/pods/workshop04_loadgenerator*/*/*.log
        - /hostfs/var/log/pods/workshop04_*/opentelemetry-auto-instrumentation*/*.log
        - /hostfs/var/log/pods/workshop04_*/otc-container/*.log
        # log.file.path
        include_file_path: true
        start_at: end

        operators:
        - type: container
          add_metadata_from_filepath: true
          on_error: drop
        - type: copy
          from: resource["k8s.pod.name"]
          to: resource["pod"]
        - type: copy
          from: resource["k8s.namespace.name"]
          to: resource["namespace"]
        - type: move
          from: attributes["log.iostream"]
          to: resource["stream"]
        - type: add 
          field: resource["service.instance.id"]
          value: EXPR(resource["k8s.namespace.name"] + "." + resource["k8s.pod.name"] + "." + resource["k8s.container.name"])
        - type: severity_parser
          parse_from: resource["stream"]
          overwrite_text: true
          mapping:
            info: stdout
            error: stderr

    exporters:
      otlp:
        endpoint: task01-otelcol-collector.workshop04.svc.cluster.local:4317
        tls:
          insecure: true

      debug:
        # basic, normal, detailed
        verbosity: detailed
        sampling_initial: 1
        sampling_thereafter: 100

    service:
      extensions: [ health_check, zpages ]
      pipelines:
        logs:
          receivers: [ filelog ]
          processors: [ batch, memory_limiter ]
          exporters: [ otlp, debug ]